### ISSUE TITLE
Is it possible to plot the lines of code of a user-customized directory/directories along with the lines of code of the whole project?

### ISSUE THREAD

**Issue by huskier** [lsk569937453/git-statistic#13]
I wonder it is possible to plot the lines of code of a user-customized directory/directories along with the lines of code of the whole project?

Sometimes, in addition to the lines of code of a project, we also want to know a specific directory's lines of code trends.

**Comment by lsk569937453** [comment]
https://github.com/lsk569937453/git-statistic/pull/16
This issue has been completed in the above pr.

**Comment by huskier** [comment]
Thank you for your effort.

In the plots by directories, could you please also add the root directory (the total lines of the project)?

BTW, there is a possible bug in current implementation. After plots by directories are drawn, when we switch to other tabs then switch back, the plots by directories have gone. We expect that the plots stay there.

**Comment by lsk569937453** [comment]
> Thank you for your effort.
> 
> In the plots by directories, could you please also add the root directory (the total lines of the project)? I think we could keep only one plot there, not two.
> 
> BTW, there is a possible bug in current implementation. After plots by directories are drawn, when we switch to other tabs then switch back, the plots by directories have gone. We expect that the plots stay there.

Thank you for your feedback and suggestions!

Root Directory Plot: I agree that including the root directory's total lines in the plot will provide a more comprehensive view of the project. I will ensure that the root directory is added, and we will consolidate it into one plot instead of two, as per your suggestion.

Bug with Plot Visibility: I have noted the bug regarding the plots disappearing when switching tabs. I'll investigate this and implement a fix in the next release to ensure the plots remain visible after switching between tabs.

Both of these improvements will be included in the upcoming release. Thank you again for your valuable input!

**Comment by huskier** [comment]
One more question, during the initial stage of selecting a git repo, does the appliation store the analyzing result into a database, say SQLite db, and then retrieve the result from the DB when we switch to the functional tabs?

**Comment by lsk569937453** [comment]
Yes, that's correct! After the user selects a repository, the application performs an analysis on the repo and stores the statistical results in an SQLite database. When the user switches between tabs, the application retrieves the relevant data from the SQLite database to display on the web page.

**Comment by lsk569937453** [comment]
> One more question, during the initial stage of selecting a git repo, does the appliation store the analyzing result into a database, say SQLite db, and then retrieve the result from the DB when we switch to the functional tabs?

The problem has been fix in https://github.com/lsk569937453/git-statistic/pull/22.

**Comment by huskier** [comment]
Thank you for your persistent dedication.
