### ISSUE TITLE
Why does git-statistic remain active in memory?

### ISSUE THREAD

**Issue by huskier** [lsk569937453/git-statistic#18]
After I close git-statistic, the application is still remain active in the memory which we can see from the Window OS's task manager utility.

**Comment by lsk569937453** [comment]
The application can only be exited by selecting 'Exit' from the tray menu on the taskbar. Please ensure to click 'Exit' in the tray for the application to close properly.

**Comment by huskier** [comment]
That's not friendly, especially when we install new updated version, the old version have to quit completely.

Is this feature intentionally designed?

**Comment by lsk569937453** [comment]
Thank you for your feedback! We understand that requiring the old version to quit completely when installing a new update may feel disruptive. This behavior was intentionally designed to ensure a smooth update process and avoid conflicts between versions.

However, since updates are being rolled out quickly, we could consider canceling or modifying the tray behavior to improve the user experience during updates. We'll review this suggestion and see if there's a more seamless approach we can implement in future releases.

We appreciate your input and will continue working on making improvements!
