### ISSUE TITLE
About the tech stack?

### ISSUE THREAD

**Issue by huskier** [lsk569937453/git-statistic#9]
GitStats uses Python + gnuplot tech stack. Gnuplot is natively written in C language.

Git-Statistic uses Rust + Tauri tech stack which is quite new! What's the graphic/plot engine for this stack?

How about the Python + Matplotlib tech stack? Matplotlib is natively written in Python itself.

Personally, I like Python + Matplotlib tech stack. Maybe I could make some contributions in this tech stack.

**Comment by lsk569937453** [comment]
The tech stack of  git-statistic is following:
- [Tauri](https://tauri.app/):The Rust framework for building desktop applications.
- [Tailwind](https://tailwindcss.com/): A utility-first CSS framework for rapid UI development.
- [Radix UI](https://www.radix-ui.com/): A set of foundational components, primitives, and tools for building accessible interfaces.
- [Echarts](https://echarts.apache.org/): A charting library for browser and Node.js.
- [git2-rs](https://github.com/rust-lang/git2-rs): A Rust library for working with Git.

I use the git2-rs to develop the git-statistic so that the user will not install dependencies like git,python,gnuplot.And it it also easy for git-statistic to convert the code to command-line application.
